using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SingleMoleculePFM.protein_models;

namespace SingleMoleculePFM.assays
{
    interface assay
    {
        /// <summary>
        /// if the energy landscape changes with time it can be advanced by a dt by calling this function
        /// </summary>
        /// <param name="dt"></param>
        void AdvanceEnergy(double dt);

        protein protein { get; }
        /// <summary>
        /// the probe bead
        /// </summary>
        particle probe { get; }
        /// <summary>
        /// free energy of the assay
        /// </summary>
        double energy { get; }
        /// <summary>
        /// forces generated by the assay on linear motion of the probe
        /// </summary>
        double[] forcesOnLinMotion { get; }
        /// <summary>
        /// forces generated by the assay on the rotation of the probe
        /// </summary>
        double[] forcesOnRotMotion { get; }
        /// <summary>
        /// size of the space increment to use to compute forces
        /// </summary>
        double dx { get; }
        /// <summary>
        /// size of the angle increment to use to compute forces
        /// </summary>
        double dtheta { get; }
    }
}